resolver: nightly-2025-12-22

packages:
- .
# - ../lsp-test-notebook

nix:
  enable: false

system-ghc: true

extra-deps:
- git: https://github.com/codedownio/sandwich
  # long-running-nodes branch
  commit: c3e16ccda384917fba1ccc5f3cf8f592415562c1
  subdirs:
  - sandwich
  - sandwich-contexts
  - sandwich-quickcheck

- git: https://github.com/codedownio/lsp-test-notebook
  # long-running-nodes branch
  commit: 2beaf14aa0502d410960b6998de6303dce4fbcf2

# - language-cpp-0.2.0.27

# - github: harpocrates/language-cpp
#   commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce
