resolver: nightly-2025-11-19

packages:
- .
# - ../lsp-test-notebook

nix:
  enable: false

system-ghc: true

extra-deps:
- git: https://github.com/codedownio/sandwich
  # long-running-nodes branch
  commit: c3e16ccda384917fba1ccc5f3cf8f592415562c1
  subdirs:
  - sandwich
  - sandwich-contexts
  - sandwich-quickcheck

- git: https://github.com/codedownio/lsp-test-helpers.git
  # main branch
  commit: 6a73e2393a1d9f21719580ce9ca0efbefabda60f

# - language-cpp-0.2.0.27

# - github: harpocrates/language-cpp
#   commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce
